baseURL = "https://aivarasguntulis.github.io/"
languageCode = "en-us"
title = "Mano Hugo Puslapis"
theme = "PaperMod"

[params]
  author = "Aivaras"
  description = "Hugo puslapis"

[[menu.main]]
  identifier = "home"
  name = "Pagrindinis"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "Apie"
  url = "/about/"
  weight = 2
